name: upload OSM XML

on:
  push:
    branches: [ "New-vs-update" ]
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        git clone https://github.com/openstreetmap/svn-archive
        python svn-archive/applications/utils/import/bulk_upload_06/bulk_upload.py -h
